### PR TITLE
Fix Graphnode bugs

### LINKED ISSUE #361: Mappings use a `FirstRegisterScheme` type that is not in the GraphQL schema
The `Controller` and `UController` mappings both use a `FirstRegisterScheme` type that is not part of the subgraph's GraphQL schema. This worked so far, since we never validated the entity types that were loaded/saved with `store.get`/`store.set`. The upcoming version of graph-node will add validation for these and will cause the subgraph to fail.

The easiest fix would be to add the `FirstRegisterScheme` type to the schema and use the generated class instead of `store.get`/`store.set` directly.

Places where this type is used:

https://github.com/daostack/subgraph/blob/1bfe764903aeeff0908e0e70063f44cf638c8860/src/mappings/Controller/mapping.ts#L181-L193

https://github.com/daostack/subgraph/blob/1bfe764903aeeff0908e0e70063f44cf638c8860/src/mappings/UController/mapping.ts#L176-L188

### PR DESCRIPTION
**Pull request by ben-kaufman**
fix #361 
and 
validate that data sources need to have different names

### CODE REVIEW

File: ops/generate-daos-subgraph.js [hunk 1]
```diff
@@ -4,14 +4,26 @@ const { migrationFileLocation: defaultMigrationFileLocation, network } = require
...
+
+  let name = contract;
+  if (ids.indexOf(contract) == -1) {
+    ids.push(contract);
+  } else if (ids.indexOf(contract+contractAddress) == -1) {
+    ids.push(contract+contractAddress);
+    name = contract+contractAddress;
+  } else {
+    return;
+  }
```
Comment (orenyodfat) [inline ops/generate-daos-subgraph.js]: how about only  do `name = contract+ contractAddress` ?

File: ops/generate-subgraph.js [hunk 2]
```diff
@@ -119,9 +120,19 @@ function combineFragments(fragments, isTemplate, addresses, missingAddresses) {
...
+    let name = contract;
+    if (ids.indexOf(contract) == -1) {
+      ids.push(contract);
+    } else if (ids.indexOf(contract+contractAddress) == -1) {
+      ids.push(contract+contractAddress);
+      name = contract+contractAddress;
+    } else {
+      return;
+    }
+
```
Comment (orenyodfat) [inline ops/generate-subgraph.js]: how about only do `name = contract+ contractAddress` ?

File: src/mappings/Controller/mapping.ts [hunk 3]
```diff
@@ -179,17 +180,12 @@ export function handleRegisterScheme(event: RegisterScheme): void {
...
+  let isFirstRegister = FirstRegisterScheme.load(avatar.toHex());
   if (isFirstRegister == null) {
     insertOrganization(event.address, avatar);
-    store.set(
-      'FirstRegisterScheme',
-      avatar.toHex(),
-      new Entity(),
-    );
+    isFirstRegister = new FirstRegisterScheme(avatar.toHex());
+    isFirstRegister.id = avatar.toHex();
```
Comment (orenyodfat) [inline src/mappings/Controller/mapping.ts]: this line is redundant as the id is set be default at line 186.

File: src/mappings/UController/mapping.ts [hunk 4]
```diff
@@ -174,17 +175,12 @@ export function handleRegisterScheme(event: RegisterScheme): void {
...
+  let isFirstRegister = FirstRegisterScheme.load(event.params._avatar.toHex());
   if (isFirstRegister == null) {
     insertOrganization(event.address, event.params._avatar);
-    store.set(
-      'FirstRegisterScheme',
-      event.params._avatar.toHex(),
-      new Entity(),
-    );
+    isFirstRegister = new FirstRegisterScheme(event.params._avatar.toHex());
+    isFirstRegister.id = event.params._avatar.toHex();
```
Comment (orenyodfat) [inline src/mappings/UController/mapping.ts]: this line is redundant as the id is set be default at line 181.

**Comment by orenyodfat** [comment]
are we sure this is the issue? the graph node version is still 0.15.1 on master.
what cause the graph node issue to appears ? @ben-kaufman 
https://github.com/daostack/subgraph/blob/master/docker-compose.yml#L4

File: ops/generate-daos-subgraph.js (hunk 1 above)
Comment (ben-kaufman) [reply ops/generate-daos-subgraph.js]: We can't because the graph node `codegen` function generates the `types` code based on the name, and we use this from our own code, so we must have at least one entity which has the original name.

File: ops/generate-subgraph.js (hunk 2 above)
Comment (ben-kaufman) [reply ops/generate-subgraph.js]: Same as above...

File: src/mappings/Controller/mapping.ts (hunk 3 above)
Comment (ben-kaufman) [reply src/mappings/Controller/mapping.ts]: removed

File: src/mappings/UController/mapping.ts (hunk 4 above)
Comment (ben-kaufman) [reply src/mappings/UController/mapping.ts]: removed

**Comment by orenyodfat** [comment]
the graph node issue "validate that data sources need to have different names" introduce at 
https://github.com/graphprotocol/graph-cli/releases/tag/v0.15.1 

please update graph-cli to use 0.15.3

**Comment by orenyodfat** [comment]
please use fixed version of graph-cli and graph-ts (remove ^)

**Comment by ben-kaufman** [comment]
I fixed the versions
